### ISSUE TITLE
start_time functionality broken

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#233]
`start_time` can optionally be specified in the start message, but doesn't seem to work.

The code in `Consumer::addTopic` is suspicious, it looks like `offsets_for_times()` is being called before adding the topic to the `PartitionList`. Also not sure it is expected to work using `RD_KAFKA_PARTITION_UA` (unassigned partition) rather than having specific `TopicPartition`s in the `PartitionList`.
Error handling for the `offsets_for_times()` call should be added. Should also log an error if the specified start time is in the future.

**Comment by michele-brambilla** [comment]
Branch ``fix-start-time`` should fix this issue. I asked Nikhil a few days ago to make sure that it works properly with Nicos. I'm working now to merge this issue with https://jira.esss.lu.se/browse/DM-983

**Comment by michele-brambilla** [comment]
I tested it, but in a trivial case. As you suggested something could still be wrong, and that's why I asked Nikhil. I'll try to verify more carefully

**Comment by matthew-d-jones** [comment]
@michele-brambilla This looks closer to working: #234
I'm still not actually getting the data I expect to be written though, investigating further.

**Comment by matthew-d-jones** [comment]
@michele-brambilla 
Ah #234 does work for me, the data wasn't being written for a different reason (the demuxer's time difference check was tripping me up as my test data had historical timestamps within the message).

**Comment by michele-brambilla** [comment]
@matthew-d-jones 
Shall we merge this fix into master before proceeding to https://jira.esss.lu.se/browse/DM-983 ? It's probably better to keep the two separate.

**Comment by matthew-d-jones** [comment]
@michele-brambilla Yes, I agree they are separate issues.
